permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: redcarpet

# 作者信息
author: 
  name: leo
  email: qifenggang@outlook.com
  link: http://www.nbops.top/
  weibo: http://www.nbops.top/
  github: https://github.com/qifenggang


# 站点信息
title: Operations
description: Operations
url: http://www.nbops.top/
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/img/face.png
favicon: /public/img/face.png


# 主题设置，自动激活某个标签
active: 读书

# 首页除了最新文章外显示分类
cates: 
  - Linux
  - MongoDB
  - Python
  - Others

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档
